// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsManageModule.Data.EF;

namespace NewsManageModule.Data.Migrations
{
    [DbContext(typeof(NMMDbContext))]
    partial class NMMDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("ProviderKey");

                    b.HasKey("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new { UserId = new Guid("742863b0-f2cb-499e-bb94-b4646526fc15"), RoleId = new Guid("068a176a-fdbf-42f0-8cdc-7cb7ce32b6fd") }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("NewsManageModule.Data.Entities.History", b =>
                {
                    b.Property<int>("HID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EditTime");

                    b.Property<int>("ID");

                    b.Property<string>("NewContent")
                        .IsRequired()
                        .IsUnicode(true);

                    b.Property<string>("NewHeader")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true);

                    b.Property<string>("OldContent")
                        .IsRequired()
                        .IsUnicode(true);

                    b.Property<string>("OldHeader")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true);

                    b.HasKey("HID");

                    b.HasIndex("ID");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("NewsManageModule.Data.Entities.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .IsUnicode(true);

                    b.Property<string>("Head")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true);

                    b.Property<DateTime>("Time");

                    b.Property<Guid>("UserId");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new { ID = 11, Content = "EURO2020 đã chính thức khép lại, mặc dù chỉ cần chươi 4 trận đấu và bị loại sớm tại vòng 1/8 nhưng siêu sao Cristiano Ronaldo - Tiền đạo đội trưởng ĐTQG Bồ Đào Nha vẫn giành danh hiệu vua phá lưới với 5 bàn thắng và một kiến tạo", Head = "C. Ronaldo giành danh hiệu vua phá lưới EURO2020", Time = new DateTime(2021, 8, 3, 1, 50, 2, 962, DateTimeKind.Utc), UserId = new Guid("742863b0-f2cb-499e-bb94-b4646526fc15"), ViewCount = 100 },
                        new { ID = 1, Content = "Rạng sáng nay, trang thông tin chính thức của tập đoàn công nghệ hàng đầu thế giới Microsoft đã chính thức ra thông báo cung cấp phiên bản dùng thử của công nghệ >NET 10 và dự kiến sẽ ra mắt bản chính thức vào khoảng tháng 12/2022.", Head = "Microsoft cho ra đời công nghệ .NET 10", Time = new DateTime(2021, 8, 3, 1, 50, 2, 962, DateTimeKind.Utc), UserId = new Guid("742863b0-f2cb-499e-bb94-b4646526fc15"), ViewCount = 96 },
                        new { ID = 2, Content = "Sau nhiều năm chờ đợi, cuối cùng LM10 - Enpulga cùng các đồng đội tại ĐTQG Argentina đã chính thức lên ngôi vô địch Copa America 2021 sau khi giành chiến thắng 1-0 trước Brazil với pha lập công duy nhất của A. Dimaria.", Head = "L. Messi cùng Argentina vô địch Copa America", Time = new DateTime(2021, 8, 3, 1, 50, 2, 962, DateTimeKind.Utc), UserId = new Guid("742863b0-f2cb-499e-bb94-b4646526fc15"), ViewCount = 1 },
                        new { ID = 3, Content = "Trận chung kết UEFA EURO 2020 khép lại với phần thắng thuộc về tân vương Azzurri sau loạt luân lưu căng thẳng. Điểm nhấn đáng chú ý là 3 cầu thủ được tung vào sân M. Rashford, B. Saka và J. Sancho - những cầu thủ da màu của ĐTQG Anh là những người bỏ lỡ cả 3 quả quyết định cuối cùng. Sau trận đấy nạn phân biệt chủng tộc lại nổi lên gắt gao hơn bao giờ hết...", Head = "Đá hỏng Penalty - 3 cầu thủ da màu của tuyển Anh bị phân biệt chủng tộc", Time = new DateTime(2021, 8, 3, 1, 50, 2, 962, DateTimeKind.Utc), UserId = new Guid("742863b0-f2cb-499e-bb94-b4646526fc15"), ViewCount = 0 },
                        new { ID = 4, Content = "Thị trường tiền ảo Bitcoins là một nền tảng - hình thức kinh doanh nổi lên đình đám trong thời gian qua với hoạt động điển hìn gắn với từ khóa Đào Bitcoin. Theo ghi nhận của chúng tôi, đến 12h trưa nay, các con số thông kê thị trường tiền ảo này có dấu hiệu giảm mạnh và chưa có tín hiệu dừng lại... ", Head = "Bitcoins bắt đầu đi xuống và có nguy cơ lụi tàn", Time = new DateTime(2021, 8, 3, 1, 50, 2, 962, DateTimeKind.Utc), UserId = new Guid("742863b0-f2cb-499e-bb94-b4646526fc15"), ViewCount = 0 },
                        new { ID = 5, Content = " Mới đấy, hình ảnh được chia sẻ rất nhiều trên MXH sau trận đấu giữu 2 ĐTQG Bồ Đào Nha với Hungary đó là việc siêu sao Cristiano Ronaldo đã có hành động đẩy chai nước COcacola của nhà tài trợ EURO2020 ra khỏi tầm camera và khuyene mọi người uống nước lọc giống anh. Ngày hôm nay, thị trường cổ phiếu ghi nhận hãng Cocacola bị giảm mạnh với mức giảm 5% giá trị cổ phiếu...", Head = "Cổ phiếu Cocacola giảm mạnh sau pha /dìm hàng/ của CR7", Time = new DateTime(2021, 8, 3, 1, 50, 2, 962, DateTimeKind.Utc), UserId = new Guid("742863b0-f2cb-499e-bb94-b4646526fc15"), ViewCount = 0 },
                        new { ID = 6, Content = "Sau 2 năm im lặng với các sản phẩm âm nhạc cảu mình, Kay Trần đã chính thức cumback với bản hit Nắm đôi bàn tay với rất nhiều những ý kiến trái chiều của CĐM xoay quanh sự ảnh hưởng của Sơn Tùng MTP....", Head = "Kay Trần quay trở lại với sản phẩm âm nhạc thuộc MTP ENtertaiments", Time = new DateTime(2021, 8, 3, 1, 50, 2, 962, DateTimeKind.Utc), UserId = new Guid("742863b0-f2cb-499e-bb94-b4646526fc15"), ViewCount = 0 },
                        new { ID = 7, Content = "Mới đây, Lionel Messi sau khi đá hỏng quả phạt đền dâng chức vô địch cho ĐTQG Chile, CĐM lại nhận được bão chia sẻ với hình ảnh Mesi hát thuộc lòng quốc ca Chile trước trận đấu...", Head = "Shock! Missi khiến người hâm mô điên đảo khi hát thuộc lòng quốc ca Chiile", Time = new DateTime(2021, 8, 3, 1, 50, 2, 962, DateTimeKind.Utc), UserId = new Guid("742863b0-f2cb-499e-bb94-b4646526fc15"), ViewCount = 7 }
                    );
                });

            modelBuilder.Entity("NewsManageModule.Data.Entities.PostInTopic", b =>
                {
                    b.Property<int>("ID");

                    b.Property<int>("TID");

                    b.HasKey("ID", "TID");

                    b.HasIndex("TID");

                    b.ToTable("PostsInTopics");

                    b.HasData(
                        new { ID = 11, TID = 11 },
                        new { ID = 1, TID = 2 },
                        new { ID = 2, TID = 11 },
                        new { ID = 3, TID = 11 },
                        new { ID = 3, TID = 1 },
                        new { ID = 3, TID = 3 },
                        new { ID = 3, TID = 5 },
                        new { ID = 3, TID = 6 },
                        new { ID = 4, TID = 4 },
                        new { ID = 5, TID = 11 },
                        new { ID = 5, TID = 4 },
                        new { ID = 6, TID = 3 },
                        new { ID = 7, TID = 11 }
                    );
                });

            modelBuilder.Entity("NewsManageModule.Data.Entities.Resource", b =>
                {
                    b.Property<int>("RID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true);

                    b.Property<long>("FileSize");

                    b.Property<int>("ID");

                    b.Property<DateTime>("ImportDate");

                    b.Property<bool>("IsAvatar");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.HasKey("RID");

                    b.HasIndex("ID");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("NewsManageModule.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new { Id = new Guid("068a176a-fdbf-42f0-8cdc-7cb7ce32b6fd"), ConcurrencyStamp = "90bbc3ff-2ddb-4470-9c59-bb566c5a858d", Name = "Staff", NormalizedName = "staff" }
                    );
                });

            modelBuilder.Entity("NewsManageModule.Data.Entities.Topic", b =>
                {
                    b.Property<int>("TID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true);

                    b.HasKey("TID");

                    b.ToTable("Topics");

                    b.HasData(
                        new { TID = 11, TName = "Thể thao" },
                        new { TID = 1, TName = "Văn hóa" },
                        new { TID = 2, TName = "Công nghệ" },
                        new { TID = 3, TName = "Showbiz" },
                        new { TID = 4, TName = "Tài chính" },
                        new { TID = 5, TName = "Pháp luật" },
                        new { TID = 6, TName = "Giáo dục" }
                    );
                });

            modelBuilder.Entity("NewsManageModule.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(true);

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = new Guid("742863b0-f2cb-499e-bb94-b4646526fc15"), AccessFailedCount = 0, ConcurrencyStamp = "2b2d3f5f-c52b-4052-93fc-fd0ba2149d56", Email = "khai12345678t@gmail.com", EmailConfirmed = true, Fullname = "Nguyen Duy Khai", LockoutEnabled = false, NormalizedEmail = "khai12345678t@gmail.com", NormalizedUserName = "itkhainddotdev", PasswordHash = "AQAAAAEAACcQAAAAEDDTS5nSk+4gR6PAxYN1Dy07XpZRsN0a3Yc4jrN87CvbXmZb5iih12qZzqXBsNoqRg==", PhoneNumberConfirmed = false, SecurityStamp = "", TwoFactorEnabled = false, UserName = "itKhaiNDdotDev" }
                    );
                });

            modelBuilder.Entity("NewsManageModule.Data.Entities.History", b =>
                {
                    b.HasOne("NewsManageModule.Data.Entities.Post", "Post")
                        .WithMany("Histories")
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NewsManageModule.Data.Entities.Post", b =>
                {
                    b.HasOne("NewsManageModule.Data.Entities.User", "Creator")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NewsManageModule.Data.Entities.PostInTopic", b =>
                {
                    b.HasOne("NewsManageModule.Data.Entities.Post", "Post")
                        .WithMany("PostInTopics")
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NewsManageModule.Data.Entities.Topic", "Topic")
                        .WithMany("PostsInTopic")
                        .HasForeignKey("TID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NewsManageModule.Data.Entities.Resource", b =>
                {
                    b.HasOne("NewsManageModule.Data.Entities.Post", "Post")
                        .WithMany("Resources")
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
